ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS asset_type TEXT NOT NULL DEFAULT 'vehicle';
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS inv_no TEXT DEFAULT '';
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS object_id TEXT DEFAULT '';
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS verified_to TEXT DEFAULT '';
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS holder TEXT DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_vehicles_type ON vehicles(asset_type);