ALTER TABLE inspection_defects ADD COLUMN IF NOT EXISTS fix_status TEXT NOT NULL DEFAULT 'не устранено';
ALTER TABLE inspection_defects ADD COLUMN IF NOT EXISTS fix_date TEXT NOT NULL DEFAULT '';
ALTER TABLE inspection_defects ADD COLUMN IF NOT EXISTS responsibility TEXT NOT NULL DEFAULT 'вопрос подрядчика';
ALTER TABLE inspection_defects ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT '';
ALTER TABLE inspection_defects ADD COLUMN IF NOT EXISTS measures TEXT NOT NULL DEFAULT '';
ALTER TABLE inspection_defects ADD COLUMN IF NOT EXISTS ack_by TEXT NOT NULL DEFAULT '';
ALTER TABLE inspection_defects ADD COLUMN IF NOT EXISTS doc_ref TEXT NOT NULL DEFAULT '';
ALTER TABLE inspection_defects ADD COLUMN IF NOT EXISTS place TEXT NOT NULL DEFAULT '';
ALTER TABLE inspection_defects ADD COLUMN IF NOT EXISTS contractor TEXT NOT NULL DEFAULT '';
ALTER TABLE inspection_defects ADD COLUMN IF NOT EXISTS extend_note TEXT NOT NULL DEFAULT '';
ALTER TABLE inspection_defects ADD COLUMN IF NOT EXISTS responsible TEXT NOT NULL DEFAULT '';

ALTER TABLE orders ADD COLUMN IF NOT EXISTS stop_works BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS fix_date TEXT NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS extend_note TEXT NOT NULL DEFAULT '';