ALTER TABLE doc_review_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE doc_review_notes FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON doc_review_notes USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE doc_review_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE doc_review_pages FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON doc_review_pages USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE doc_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE doc_reviews FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON doc_reviews USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON documents USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE equipment_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE equipment_items FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON equipment_items USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE equipment_moves ENABLE ROW LEVEL SECURITY;
ALTER TABLE equipment_moves FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON equipment_moves USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE fleet_acts ENABLE ROW LEVEL SECURITY;
ALTER TABLE fleet_acts FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON fleet_acts USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE fleet_days ENABLE ROW LEVEL SECURITY;
ALTER TABLE fleet_days FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON fleet_days USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));