ALTER TABLE fleet_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE fleet_expenses FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON fleet_expenses USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE fleet_maint ENABLE ROW LEVEL SECURITY;
ALTER TABLE fleet_maint FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON fleet_maint USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE fleet_repairs ENABLE ROW LEVEL SECURITY;
ALTER TABLE fleet_repairs FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON fleet_repairs USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE fleet_shifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE fleet_shifts FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON fleet_shifts USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE folder_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE folder_photos FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON folder_photos USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE inspection_defects ENABLE ROW LEVEL SECURITY;
ALTER TABLE inspection_defects FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON inspection_defects USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE inspections ENABLE ROW LEVEL SECURITY;
ALTER TABLE inspections FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON inspections USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE inspector_journal ENABLE ROW LEVEL SECURITY;
ALTER TABLE inspector_journal FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON inspector_journal USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE locations FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON locations USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE object_contractors ENABLE ROW LEVEL SECURITY;
ALTER TABLE object_contractors FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON object_contractors USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE object_docs ENABLE ROW LEVEL SECURITY;
ALTER TABLE object_docs FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON object_docs USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE object_load ENABLE ROW LEVEL SECURITY;
ALTER TABLE object_load FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON object_load USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE objects ENABLE ROW LEVEL SECURITY;
ALTER TABLE objects FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON objects USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON orders USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE part_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE part_requests FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON part_requests USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));
ALTER TABLE photo_folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE photo_folders FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON photo_folders USING (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi')) WITH CHECK (company_id = coalesce(nullif(current_setting('app.company',true),''),'gsi'));