CREATE INDEX IF NOT EXISTS idx_co_cabinet_archive ON cabinet_archive (company_id);
CREATE INDEX IF NOT EXISTS idx_co_contract_acts ON contract_acts (company_id);
CREATE INDEX IF NOT EXISTS idx_co_contractors ON contractors (company_id);
CREATE INDEX IF NOT EXISTS idx_co_contracts ON contracts (company_id);
CREATE INDEX IF NOT EXISTS idx_co_cust_letters ON cust_letters (company_id);
CREATE INDEX IF NOT EXISTS idx_co_cust_points ON cust_points (company_id);
CREATE INDEX IF NOT EXISTS idx_co_cust_replies ON cust_replies (company_id);
CREATE INDEX IF NOT EXISTS idx_co_daily_inspector_reports ON daily_inspector_reports (company_id);
CREATE INDEX IF NOT EXISTS idx_co_daily_reports ON daily_reports (company_id);
CREATE INDEX IF NOT EXISTS idx_co_doc_checks ON doc_checks (company_id);
CREATE INDEX IF NOT EXISTS idx_co_doc_defects ON doc_defects (company_id);
CREATE INDEX IF NOT EXISTS idx_co_doc_files ON doc_files (company_id);
CREATE INDEX IF NOT EXISTS idx_co_doc_review_files ON doc_review_files (company_id);
CREATE INDEX IF NOT EXISTS idx_co_doc_review_notes ON doc_review_notes (company_id);
CREATE INDEX IF NOT EXISTS idx_co_doc_review_pages ON doc_review_pages (company_id);
CREATE INDEX IF NOT EXISTS idx_co_doc_reviews ON doc_reviews (company_id);
CREATE INDEX IF NOT EXISTS idx_co_documents ON documents (company_id);
CREATE INDEX IF NOT EXISTS idx_co_equipment_items ON equipment_items (company_id);
CREATE INDEX IF NOT EXISTS idx_co_equipment_moves ON equipment_moves (company_id);
CREATE INDEX IF NOT EXISTS idx_co_fleet_acts ON fleet_acts (company_id);
CREATE INDEX IF NOT EXISTS idx_co_fleet_days ON fleet_days (company_id);
CREATE INDEX IF NOT EXISTS idx_co_fleet_expenses ON fleet_expenses (company_id);
CREATE INDEX IF NOT EXISTS idx_co_fleet_maint ON fleet_maint (company_id);
CREATE INDEX IF NOT EXISTS idx_co_fleet_repairs ON fleet_repairs (company_id);
CREATE INDEX IF NOT EXISTS idx_co_fleet_shifts ON fleet_shifts (company_id);
CREATE INDEX IF NOT EXISTS idx_co_folder_photos ON folder_photos (company_id);
CREATE INDEX IF NOT EXISTS idx_co_inspection_defects ON inspection_defects (company_id);
CREATE INDEX IF NOT EXISTS idx_co_inspections ON inspections (company_id);
CREATE INDEX IF NOT EXISTS idx_co_inspector_journal ON inspector_journal (company_id);
CREATE INDEX IF NOT EXISTS idx_co_locations ON locations (company_id);
CREATE INDEX IF NOT EXISTS idx_co_object_contractors ON object_contractors (company_id);
CREATE INDEX IF NOT EXISTS idx_co_object_docs ON object_docs (company_id);
CREATE INDEX IF NOT EXISTS idx_co_object_load ON object_load (company_id);
CREATE INDEX IF NOT EXISTS idx_co_objects ON objects (company_id);
CREATE INDEX IF NOT EXISTS idx_co_orders ON orders (company_id);
CREATE INDEX IF NOT EXISTS idx_co_part_requests ON part_requests (company_id);
CREATE INDEX IF NOT EXISTS idx_co_photo_folders ON photo_folders (company_id);
CREATE INDEX IF NOT EXISTS idx_co_ppe_items ON ppe_items (company_id);
CREATE INDEX IF NOT EXISTS idx_co_ppe_writeoffs ON ppe_writeoffs (company_id);
CREATE INDEX IF NOT EXISTS idx_co_project_fields ON project_fields (company_id);
CREATE INDEX IF NOT EXISTS idx_co_requests ON requests (company_id);
CREATE INDEX IF NOT EXISTS idx_co_signed_docs ON signed_docs (company_id);
CREATE INDEX IF NOT EXISTS idx_co_timesheet ON timesheet (company_id);
CREATE INDEX IF NOT EXISTS idx_co_track_consent ON track_consent (company_id);
CREATE INDEX IF NOT EXISTS idx_co_track_days ON track_days (company_id);
CREATE INDEX IF NOT EXISTS idx_co_track_points ON track_points (company_id);
CREATE INDEX IF NOT EXISTS idx_co_users ON users (company_id);
CREATE INDEX IF NOT EXISTS idx_co_vehicle_logs ON vehicle_logs (company_id);
CREATE INDEX IF NOT EXISTS idx_co_vehicles ON vehicles (company_id);
CREATE INDEX IF NOT EXISTS idx_co_waybills ON waybills (company_id);
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_fio_key_key;
CREATE UNIQUE INDEX IF NOT EXISTS users_company_fio_key ON users (company_id, fio_key);
ALTER TABLE settings DROP CONSTRAINT IF EXISTS settings_pkey;
ALTER TABLE settings ADD PRIMARY KEY (company_id, key);
ALTER TABLE track_month DROP CONSTRAINT IF EXISTS track_month_uniq;
DROP INDEX IF EXISTS track_month_uniq;
CREATE UNIQUE INDEX IF NOT EXISTS track_month_company_ym ON track_month (company_id, ym);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS access_code TEXT NOT NULL DEFAULT '';
CREATE UNIQUE INDEX IF NOT EXISTS companies_access_code ON companies (access_code) WHERE access_code <> '';